name: Master QA Pipeline

on:
  pull_request:
    branches:
      - qa
  push:
    branches:
      - qa

jobs:
  authentication:
    uses: ./authentication/org/authentication.yml
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}

  validation:
    needs: authentication
    if: github.event_name == 'pull_request' && github.base_ref == 'qa'
    uses: ./validation/org/validation.yml
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}

  deployment:
    needs: validation
    if: github.event_name == 'push' && github.ref == 'refs/heads/qa'
    uses: ./deployment/org/deployment.yml
    secrets:
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      SERVER_KEY: ${{ secrets.SERVER_KEY }}
      SF_USERNAME: ${{ secrets.SF_USERNAME }}
      SF_INSTANCE_URL: ${{ secrets.SF_INSTANCE_URL }}
